### ISSUE TITLE
App doesn't add buttons to slack messages?

### ISSUE THREAD

**Issue by mattnovelli** [wilsonpage/songwhip-slack#4]
Howdy,
I installed this app to my slack workspace and this is the result when I send a song:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/5261716/214988241-79c205c0-5e79-479c-9106-aacdb5eb52f3.png">
This is what the songwhip website displays:
![image](https://user-images.githubusercontent.com/5261716/214988478-f05ea2fe-6ae6-4ac8-97df-52982969605b.png)
How can I get that?

**Comment by wilsonpage** [comment]
Hey man, sorry for the confusion. You were looking at the V2 Slack App that hadn't been released yet.

Good new is, it just got released this morning and can be installed via:
https://slack.songwhip.com/add

You might be the first person to try it! LMK what you think :)

PS. If things don't work quite right, try removing the old app then installing fresh.
